### ISSUE TITLE
Fix NullPointerException in ui.activities.WebActivity.onOpenInBrowser, line 233

### ISSUE THREAD

**Issue by Vovchyk** [Vovchyk/android-rss-feed-reader#125]
### Stacktrace ###

<pre>ui.activities.WebActivity;onOpenInBrowser;WebActivity.java;233
ui.activities.WebActivity;onOptionsItemSelected;WebActivity.java;182</pre>

### Reason ###

java.lang.NullPointerException: Attempt to invoke virtual method 'void rss.feed.reader.Navigation.toWebBrowser(java.lang.String)' on a null object reference

### Link to HockeyApp ###

* [https://rink.hockeyapp.net/manage/apps/456319/crash_reasons/195228901](https://rink.hockeyapp.net/manage/apps/456319/crash_reasons/195228901)

**Comment by qUser13** [comment]
No longer reproducible on 1.0.54
